let currentUser=null,csrfToken='',tripEpoch=0,runningJobId=null,authMode='login',pendingRecovery='',tripItems=[],tripOffset=0,tripTotal=0,tripTarget=null,tripMutation='rename',historyRequest=0;
const aq=s=>document.querySelector(s);
let toastTimer;
function toast(text){const root=aq('#toast'),card=document.createElement('div');root.hidden=false;card.className='toast-card';card.textContent=text;root.append(card);while(root.children.length>3)root.firstElementChild.remove();setTimeout(()=>{card.classList.add('fading');setTimeout(()=>{card.remove();root.hidden=!root.children.length},600)},4200);}
function formError(id,text=''){const el=aq('#'+id);el.textContent=text;el.hidden=!text}
function closeHistory(){aq('#trips-dialog').hidden=true;aq('#application').classList.remove('history-open');aq('#history-toggle').setAttribute('aria-expanded','false')}
function closeDialogs(){closeHistory();document.querySelectorAll('dialog[open]').forEach(d=>d.close())}
function showGate(message=''){
 tripEpoch++;pendingRecovery='';aq('#recovery-code').value='';aq('#recovery-reminder').hidden=true;currentUser=null;csrfToken='';runningJobId=null;jobUI=null;workspace=null;setBusy(false);closeDialogs();aq('#messages').replaceChildren();aq('#content').replaceChildren();aq('#message').value='';aq('#application').hidden=true;aq('#auth-gate').hidden=false;
 for(const id of ['trips-button','new','account-button'])aq('#'+id).hidden=true;
 aq('#connection').textContent='旅游规划助手';formError('auth-error',message);
}
function acceptSession(data){clearTimeout(toastTimer);aq('#toast').replaceChildren();aq('#toast').hidden=true;currentUser=data.user;csrfToken=data.csrf_token;aq('#application').hidden=false;aq('#auth-gate').hidden=true;for(const id of ['trips-button','new','account-button'])aq('#'+id).hidden=false;aq('#account-button').textContent=currentUser.nickname;aq('#connection').textContent='自动保存 · 个人旅行空间';}
async function bootAccount(){try{const data=await api('/api/auth/me');acceptSession(data);await loadWorkspace()}catch(e){showGate(e.code===401?'':e.message);if(e.code!==401)formError('auth-error','暂时无法连接服务，请确认项目已经启动，再刷新页面。')}}
function draftKey(wid){return 'shitu-draft:'+currentUser.id+':'+wid}
async function loadWorkspace(wid=null,provided=null){
 if(!currentUser)return;const uid=currentUser.id;if(workspace)sessionStorage.setItem(draftKey(workspace.id),aq('#message').value);const epoch=++tripEpoch;runningJobId=null;jobUI=null;setBusy(false);error('');aq('#reconnect-task').hidden=true;
 let w=provided;
 if(!w){const saved=wid||localStorage.getItem('shitu-current:'+uid);if(saved){try{w=await api('/api/workspaces/'+saved)}catch(e){if(e.code!==404)throw e}}if(!w)w=await api('/api/workspaces/latest')}
 if(epoch!==tripEpoch||currentUser?.id!==uid)return;workspace=w;liveReply='';liveSteps=[];setWorkbenchExpanded(false);destinationPage=1;transportDates={};controlsSignature='';referenceFocus=null;lastPanelKey='';foodAnchor='';mapDay='';mealDate='';mealPeriod='lunch';transportMode=w.transport?.kind||'train';transportDirection=w.ui?.action==='complete_hotel'?'outbound':w.transport?.direction||'outbound';trainType=w.query_controls?.train_type||'all';timeStart=w.query_controls?.time_start||'';timeEnd=w.query_controls?.time_end||'';jobUI=w.active_job?.ui||null;tab=sceneNames[jobUI?.view]?jobUI.view:initialView(w);renderedMessages='';detailOpenId=null;aq('#message').value=sessionStorage.getItem(draftKey(w.id))||'';localStorage.setItem('shitu-current:'+uid,w.id);render();
 if(w.active_job){aq('#progress-text').textContent=w.active_job.progress;void pollJob(w.id,w.active_job.id,epoch)}
}
async function newTrip(){try{const w=await api('/api/workspaces',{method:'POST'});closeDialogs();await loadWorkspace(w.id,w);toast('已开始一段新旅行，旧旅行保留在“我的旅行”中。');aq('#message').focus()}catch(e){toast(e.message)}}
function setAuthMode(mode){authMode=mode;formError('auth-error');aq('#auth-title').textContent=mode==='register'?'开始你的旅行空间':mode==='recover'?'恢复你的账户':'欢迎回来';aq('#auth-intro').textContent=mode==='register'?'不同旅行独立保存，回来就能继续。':mode==='recover'?'使用已保存的恢复码，设置新密码。':'登录后，继续安排你的旅行。';aq('#nickname-label').hidden=mode!=='register';aq('#recovery-label').hidden=mode!=='recover';aq('#auth-recovery').required=mode==='recover';aq('#auth-password').autocomplete=mode==='login'?'current-password':'new-password';aq('#auth-submit').textContent=mode==='register'?'注册并开始':mode==='recover'?'重置密码并登录':'登录并继续';aq('#auth-login-tab').classList.toggle('active',mode==='login');aq('#auth-register-tab').classList.toggle('active',mode==='register');}
aq('#auth-login-tab').onclick=()=>setAuthMode('login');aq('#auth-register-tab').onclick=()=>setAuthMode('register');aq('#forgot-password').onclick=()=>setAuthMode('recover');
aq('#auth-form').onsubmit=async e=>{
 e.preventDefault();formError('auth-error');aq('#auth-submit').disabled=true;
 try{const username=aq('#auth-username').value.trim(),password=aq('#auth-password').value;let body={username,password};if(authMode==='register')body.nickname=aq('#auth-nickname').value.trim();if(authMode==='recover')body={username,recovery_code:aq('#auth-recovery').value.trim(),new_password:password};const data=await api('/api/auth/'+(authMode==='recover'?'recover':authMode),{method:'POST',body:JSON.stringify(body)});acceptSession(data);aq('#auth-password').value='';aq('#auth-recovery').value='';await loadWorkspace();if(data.recovery_code)showRecovery(data.recovery_code)}catch(e){formError('auth-error',e.message)}finally{aq('#auth-submit').disabled=false}
};
function showRecovery(code){pendingRecovery=code;aq('#recovery-code').value=code;aq('#recovery-dialog').showModal()}
aq('#recovery-dialog').addEventListener('cancel',()=>setTimeout(()=>{aq('#recovery-reminder').hidden=!pendingRecovery},0));
aq('#download-recovery').onclick=()=>{const data=`识途账户恢复码\n用户名：${currentUser.username}\n恢复码：${pendingRecovery}\n请妥善保存。更新恢复码或使用其重置密码后，本码将失效。\n`;const url=URL.createObjectURL(new Blob([data],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='识途-账户恢复码.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
aq('#recovery-saved').onclick=()=>{pendingRecovery='';aq('#recovery-code').value='';aq('#recovery-dialog').close()};

async function refreshHistory(append=false){
 const request=++historyRequest,offset=append?tripOffset:0;aq('#more-trips').disabled=true;
 try{const d=await api(`/api/workspaces?q=${encodeURIComponent(aq('#trip-search').value.trim())}&archived=${aq('#trip-filter').value==='archived'}&offset=${offset}`);if(request!==historyRequest)return;tripItems=append?tripItems.concat(d.items):d.items;tripOffset=offset+d.items.length;tripTotal=d.total;renderHistory()}catch(e){if(request===historyRequest)aq('#trip-list').textContent=e.message}finally{aq('#more-trips').disabled=false}
}
function renderHistory(){aq('#trip-list').innerHTML=tripItems.length?tripItems.map(t=>`<article class="trip-item ${workspace?.id===t.id?'current-trip':''}"><button class="trip-open" data-trip-open="${esc(t.id)}"><strong>${esc(t.title)}</strong><span>${esc(t.city||'目的地待定')} · ${esc(t.date||'日期待定')}${t.days?' · '+t.days+'天':''}</span><small>${t.running?'正在处理 · 可回到进度':t.has_plan?t.stale?'已有计划 · 待更新':'已有计划书':'需求与选择中'} · ${t.messages}条对话</small></button><div class="trip-operations"><button data-trip-rename="${esc(t.id)}">重命名</button><button data-trip-archive="${esc(t.id)}">${t.archived?'恢复':'归档'}</button><button class="delete-trip" data-trip-delete="${esc(t.id)}">删除</button></div></article>`).join(''):'<div class="history-empty">没有匹配的旅行。可以开始新旅行，或查看已归档记录。</div>';aq('#more-trips').hidden=tripOffset>=tripTotal}
async function openHistory(){if(!aq('#trips-dialog').hidden){closeHistory();return}aq('#trips-dialog').hidden=false;aq('#application').classList.add('history-open');aq('#history-toggle').setAttribute('aria-expanded','true');await refreshHistory()}
aq('#history-toggle').onclick=openHistory;
aq('#trips-button').onclick=openHistory;aq('#conversation-history').onclick=openHistory;aq('#drawer-new').onclick=newTrip;aq('#more-trips').onclick=()=>refreshHistory(true);aq('#trip-filter').onchange=()=>refreshHistory();let searchTimer;aq('#trip-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>refreshHistory(),250)};
async function mutateTrip(id,kind){
 try{tripTarget=await api('/api/workspaces/'+id);tripMutation=kind;
  if(kind==='archive'){const w=await api('/api/workspaces/'+id,{method:'PATCH',body:JSON.stringify({revision:tripTarget.revision,archived:!tripTarget.archived})});if(workspace?.id===id)await loadWorkspace(id,w);await refreshHistory();toast(w.archived?'旅行已归档，可以在归档列表找回。':'已恢复这次旅行。');return}
  aq('#trip-edit-title').textContent=kind==='rename'?'给旅行起个名字':'删除这次旅行';aq('#trip-edit-description').textContent=kind==='rename'?'名称方便你在历史列表中找回旅行。':`将删除「${tripTarget.title}」的对话、选择和计划记录，此操作不能撤销。`;aq('#trip-name-label').hidden=kind!=='rename';aq('#trip-name-input').required=kind==='rename';aq('#trip-name-input').value=tripTarget.title;aq('#trip-edit-submit').textContent=kind==='rename'?'保存名称':'确认删除';aq('#trip-edit-submit').classList.toggle('danger',kind==='delete');formError('trip-edit-error');aq('#trip-edit').showModal();
 }catch(e){toast(e.message)}
}
aq('#trip-edit-form').onsubmit=async e=>{e.preventDefault();aq('#trip-edit-submit').disabled=true;formError('trip-edit-error');try{const id=tripTarget.id;if(tripMutation==='delete'){await api('/api/workspaces/'+id,{method:'DELETE'});if(workspace?.id===id){localStorage.removeItem('shitu-current:'+currentUser.id);sessionStorage.removeItem(draftKey(id));workspace=null;await loadWorkspace()}}else{const w=await api('/api/workspaces/'+id,{method:'PATCH',body:JSON.stringify({title:aq('#trip-name-input').value.trim(),revision:tripTarget.revision})});if(workspace?.id===id){workspace=w;render()}}aq('#trip-edit').close();await refreshHistory();toast(tripMutation==='delete'?'旅行记录已删除。':'旅行名称已保存。')}catch(e){formError('trip-edit-error',e.message)}finally{aq('#trip-edit-submit').disabled=false}};

function openAccount(){formError('account-error');aq('#account-identity').textContent=`${currentUser.username} · 加入时间 ${currentUser.created.slice(0,10)}`;aq('#profile-nickname').value=currentUser.nickname;for(const id of ['password-form','recovery-form','delete-account-form'])aq('#'+id).reset();aq('#account-dialog').showModal()}
aq('#account-button').onclick=openAccount;
aq('#profile-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/auth/profile',{method:'PATCH',body:JSON.stringify({nickname:aq('#profile-nickname').value.trim()})});currentUser=d.user;aq('#account-button').textContent=currentUser.nickname;formError('account-error');toast('昵称已保存。')}catch(e){formError('account-error',e.message)}};
aq('#password-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/auth/password',{method:'POST',body:JSON.stringify({current_password:aq('#old-password').value,new_password:aq('#new-password').value})});acceptSession(d);e.target.reset();formError('account-error');toast('密码已更新，其他登录已失效。')}catch(e){formError('account-error',e.message)}};
aq('#recovery-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/auth/recovery-code',{method:'POST',body:JSON.stringify({password:aq('#recovery-password').value})});e.target.reset();formError('account-error');showRecovery(d.recovery_code)}catch(e){formError('account-error',e.message)}};
function clearDrafts(){const prefix='shitu-draft:'+currentUser.id+':';Object.keys(sessionStorage).filter(k=>k.startsWith(prefix)).forEach(k=>sessionStorage.removeItem(k))}
aq('#logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'});clearDrafts();showGate();toast('已退出登录。你的旅行记录保留在账户中。')}catch(e){formError('account-error',e.message)}};
aq('#delete-account-form').onsubmit=async e=>{e.preventDefault();if(!aq('#delete-confirm').checked)return;try{await api('/api/account',{method:'DELETE',body:JSON.stringify({password:aq('#delete-password').value})});clearDrafts();localStorage.removeItem('shitu-current:'+currentUser.id);showGate();toast('账户与当前数据库中的旅行记录已注销。')}catch(e){formError('account-error',e.message)}};
aq('#cancel-task').onclick=async()=>{if(!runningJobId)return;try{await api('/api/jobs/'+runningJobId+'/cancel',{method:'POST'});aq('#progress-text').textContent='正在停止本轮处理…'}catch(e){error(e.message)}};
aq('#reconnect-task').onclick=async()=>{try{await loadWorkspace(workspace?.id)}catch(e){error(e.message)}};
aq('#message').addEventListener('input',()=>{if(currentUser&&workspace)sessionStorage.setItem(draftKey(workspace.id),aq('#message').value)});

const helpContent='<h3>怎样开始一次旅行？</h3><p>点“新旅行”，告诉识途目的地、同行人和偏好。先选景点，再比较住宿与往返交通，最后生成计划书。</p><h3>怎么找回之前的对话？</h3><p>点“我的旅行”或对话区的“历史”，选择一条记录继续。不同旅行的条件、聊天和计划各自保存。归档记录可以恢复，删除则不能撤销。</p><h3>任务还在处理时能离开吗？</h3><p>可以切换到其他旅行或刷新页面。回到这次旅行时会恢复任务进度，也可以点“停止”。服务重启会使未完成任务中断，已保存的对话和选择仍保留。</p><h3>计划能直接拿去执行吗？</h3><p>先检查待确认事项和来源日期。选择住宿或班次并不代表已预订；门票预约、接驳、完整费用等未核实项需要确认。当前知识资料主要覆盖青岛。</p><h3>忘记密码怎么办？</h3><p>在登录页使用注册时保存的恢复码重置密码。恢复成功后会生成新的恢复码，旧码失效。邮件、短信验证尚未接入；丢失密码和恢复码时，需要本机管理员协助恢复。</p>';
const privacyContent='<h3>保存哪些信息</h3><p>账户保存用户名、昵称、密码哈希及恢复码哈希；旅行会话保存你提交的需求、对话、候选、选择与计划。登录凭证存放在浏览器的HttpOnly Cookie中。未发送的输入暂存在本浏览器会话，退出登录会清除。</p><h3>外部模型与数据服务</h3><p>完成规划时，相关旅行需求、候选和近期对话会传给配置的大语言模型；地点、日期和查询条件会传给对应的地图、天气或途牛服务。请避免输入身份证号、支付信息、密码或恢复码。</p><h3>账户隔离与删除</h3><p>登录后只能访问自己的旅行和任务。可导出账户数据、删除单次旅行或注销账户。当前数据保存在本机项目数据库中；管理员已有的备份不随网页删除，公开部署前需明确备份保留和清理流程。</p><h3>当前运行范围</h3><p>本项目现阶段用于本机开发与验证。公网服务所需的邮件短信服务、正式隐私政策、运营支持、部署与备份策略仍需配置和审核。本说明描述当前功能，不是已完成上线审核的声明。</p>';
function showInfo(kind){closeHistory();aq('#info-title').textContent=kind==='privacy'?'数据与使用说明':'使用帮助';aq('#info-content').innerHTML=kind==='privacy'?privacyContent:helpContent;aq('#info-dialog').showModal()}
async function openFeedback(){closeHistory();aq('#feedback-dialog').showModal();formError('feedback-error');try{const d=await api('/api/feedback');aq('#feedback-list').innerHTML=d.items.map(x=>`<div class="feedback-item"><small>${esc(x.created)} · 已收录</small><p>${esc(x.content)}</p></div>`).join('')||'<p>还没有提交反馈。</p>'}catch(e){formError('feedback-error',e.message)}}
aq('#feedback-button').onclick=openFeedback;
aq('#feedback-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/feedback',{method:'POST',body:JSON.stringify({category:aq('#feedback-category').value,content:aq('#feedback-content').value.trim()})});e.target.reset();toast('反馈已保存。');await openFeedback()}catch(e){formError('feedback-error',e.message)}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close){if(b.dataset.close==='trips-dialog')closeHistory();else aq('#'+b.dataset.close).close();return}if(b.dataset.info){showInfo(b.dataset.info);return}if(b.dataset.tripOpen){try{await loadWorkspace(b.dataset.tripOpen);closeHistory()}catch(e){toast(e.message)}return}if(b.dataset.tripRename)return mutateTrip(b.dataset.tripRename,'rename');if(b.dataset.tripArchive)return mutateTrip(b.dataset.tripArchive,'archive');if(b.dataset.tripDelete)return mutateTrip(b.dataset.tripDelete,'delete');if(b.id==='restore-trip'){try{const w=await api('/api/workspaces/'+workspace.id,{method:'PATCH',body:JSON.stringify({revision:workspace.revision,archived:false})});await loadWorkspace(w.id,w)}catch(e){error(e.message)}}});
