/* Workbench state follows actual tool arguments; navigation never performs a selection. */
let controlsSignature='',referenceFocus=null,lastPanelKey='',recoveryDeferred=false;
const nativeToast=toast;
toast=function(text){const root=$('#workbench-notices');if(!root||!workspace||document.querySelector('dialog[open]'))return nativeToast(text);const item=document.createElement('div');item.className='workbench-toast';item.textContent=text;root.append(item);while(root.children.length>3)root.firstElementChild.remove();setTimeout(()=>{item.classList.add('fading');setTimeout(()=>item.remove(),450)},4800)};

function planningNavigation(){const w=workspace,r=w.requirements;const entries=[['spot','景点',!!w.spots_confirmed],['hotel','住宿',selectedStayUsable()||!!w.stay_skipped||Number(r.days)===1],['transport','交通',!!w.local_trip||!!w.selected_transport&&!!w.selected_return||r.origin&&r.origin===r.city],['food','餐饮',!!Object.keys(w.meal_choices||{}).length],['weather','天气',!!w.weather],['plan','计划',!!w.plan&&!w.plan.stale]];return entries.map(([view,title,done],i)=>`<button data-tab="${view}" class="flow-step ${tab===view?'current':''} ${done?'done':''}" aria-current="${tab===view?'step':'false'}"><span>${done?'✓':String(i+1).padStart(2,'0')}</span><strong>${title}</strong></button>`).join('')}

function descriptionHTML(p){return `<details class="spot-description" data-description="${esc(p.id)}"><summary><span class="description-preview">${esc(p.recommendation)}</span><span class="description-toggle">展开介绍</span></summary><div class="description-more"><p>${esc(p.address||'位置资料待完善')}</p>${(p.evidence||[]).slice(0,2).map(e=>`<p>${esc(e.text?.slice(0,320))}</p>`).join('')}<p>游览建议与开放资料需结合出行日期核对。</p></div></details>`}
function groupedSpotsHTML(items){let grouped=workspace.spot_groups||[];if(!grouped.length)return items.map(spotCard).join('');const ids=new Set(items.map(p=>p.id));const output=grouped.filter(g=>g.ids.some(id=>ids.has(id))||ids.has(g.parent_id)).map(g=>{const parent=workspace.catalog[g.parent_id],children=g.ids.filter(id=>id!==g.parent_id).map(id=>workspace.catalog[id]).filter(Boolean);if(children.length===0||!g.basis&&g.ids.length===1)return spotCard(parent||workspace.catalog[g.ids[0]]);return `<section class="spot-branch" data-branch="${esc(g.key)}"><div class="branch-heading"><small>${esc(g.basis||'景区内地点')}</small><h3>${esc(g.title)}</h3></div>${parent?spotCard(parent):''}<details class="branch-children" data-branch-children="${esc(g.key)}" ${children.some(p=>workspace.selected_spots.includes(p.id))?'open':''}><summary>景区内 ${children.length} 处地点</summary><div>${children.map(spotCard).join('')}</div></details></section>`});if(referenceFocus&&workspace.catalog[referenceFocus]&&!ids.has(referenceFocus))output.unshift(`<div class="referenced-item"><small>对话引用的地点</small>${spotCard(workspace.catalog[referenceFocus])}</div>`);return output.join('')}

function resolveReference(label,context){const plain=document.createElement('span');plain.innerHTML=label;const name=plain.textContent.trim();const norm=s=>String(s||'').replace(/[\s·•（）()]/g,'');const candidates=Object.values(workspace?.catalog||{}).filter(p=>p.name===name||norm(p.name)===norm(name));if(candidates.length===1){const p=candidates[0];return {view:({spot:'spot',hotel:'hotel',food:'food',train:'transport',flight:'transport'})[p.kind],id:p.id,kind:'candidate'}}const hotelIds=[workspace?.hotel?.id,...(workspace?.hotel_query?.ids||[])].filter(Boolean);let rooms=[];for(const hid of new Set(hotelIds)){const h=workspace.catalog[hid];for(const c of h?.room_choices||[]){if(c.name===name||norm(c.name)===norm(name))rooms.push({view:'hotel',id:hid,kind:'room',group:hid+':'+c.room_index})}}const preferred=context?.focus_id||workspace?.hotel?.id||detailOpenId;if(preferred&&rooms.some(r=>r.id===preferred))rooms=rooms.filter(r=>r.id===preferred);const unique=[...new Map(rooms.map(r=>[r.group,r])).values()];return unique.length===1?unique[0]:null}
const originalMessageHTML=messageHTML;
messageHTML=function(text,context){return originalMessageHTML(text).replace(/<strong>(.*?)<\/strong>/g,(all,label)=>{const ref=resolveReference(label,context);return ref?.view?`<button class="inline-reference" data-reference="${esc(ref.id)}" data-reference-view="${ref.view}" ${ref.group?`data-reference-group="${esc(ref.group)}"`:''} title="在右侧查看">${label}<span aria-hidden="true">↗</span></button>`:all})};

function positionHandle(){const panel=$('.workspace'),grip=$('#expand-workbench');if(!panel||!grip)return;const r=panel.getBoundingClientRect();grip.hidden=innerWidth<701&&!workbenchExpanded&&(r.top>innerHeight||r.bottom<60);grip.style.left=Math.max(6,r.left-31)+'px';grip.style.top=Math.min(innerHeight-62,Math.max(110,r.top+180))+'px'}
const baseExpand=setWorkbenchExpanded;
setWorkbenchExpanded=function(value){baseExpand(value);positionHandle()};
const baseRender=render;
render=function(){const root=$('#content'),key=workspace?.id+':'+tab,same=key===lastPanelKey,scroll=root?.scrollTop||0;const opened=same?[...root.querySelectorAll('details[open]')].map(d=>[d.dataset.description||d.dataset.branchChildren||d.closest('[data-candidate]')?.dataset.candidate||'',d.querySelector('summary')?.textContent]):[];baseRender();if(same){for(const d of root.querySelectorAll('details')){const k=d.dataset.description||d.dataset.branchChildren||d.closest('[data-candidate]')?.dataset.candidate||'';if(opened.some(([id,summary])=>id===k&&summary===d.querySelector('summary')?.textContent))d.open=true}root.style.scrollBehavior='auto';root.scrollTop=scroll;root.style.scrollBehavior=''}lastPanelKey=key;positionHandle()};
window.addEventListener('resize',positionHandle);window.addEventListener('scroll',positionHandle,{passive:true});

function scrollToResults(){const root=$('#content'),target=root?.querySelector('.transport-results')||root?.querySelector('.transport-summary')?.nextElementSibling;if(target){root.scrollTo({top:root.scrollTop+target.getBoundingClientRect().top-root.getBoundingClientRect().top-12,behavior:'smooth'});target.classList.add('just-updated');setTimeout(()=>target.classList.remove('just-updated'),1600)}}
async function applyQueryControls(controls,animate=false,epoch=tripEpoch){if(!controls)return;const signature=JSON.stringify(controls);if(animate&&signature===controlsSignature)return;controlsSignature=signature;const steps=[()=>{transportMode=controls.kind||'train';tab='transport'},()=>{transportDirection=controls.direction||'outbound';transportDates[transportDirection]=controls.departure_date},()=>{timeStart=controls.time_start||'';timeEnd=controls.time_end||''},()=>{trainType=controls.train_type||'all'}];for(let i=0;i<steps.length;i++){if(epoch!==tripEpoch)return;steps[i]();render();const targets=[['[data-transport-mode="'+transportMode+'"]'],['[data-transport-direction="'+transportDirection+'"]','#transport-date'],['#time-start','#time-end'],['#train-type']][i];for(const selector of targets)$(selector)?.classList.add('agent-setting');if(animate)await new Promise(r=>setTimeout(r,130))}document.querySelectorAll('.agent-setting').forEach(el=>setTimeout(()=>el.classList.remove('agent-setting'),800))}

document.addEventListener('click',e=>{const ref=e.target.closest('[data-reference]');if(!ref)return;const id=ref.dataset.reference,view=ref.dataset.referenceView,p=workspace.catalog[id];if(view==='spot')referenceFocus=id;if(view==='transport'&&p){transportMode=p.kind;transportDirection=p.direction||'outbound'}if(view==='hotel')detailOpenId=id;tab=view;render();if(ref.dataset.referenceGroup){openCandidate(id,ref.dataset.referenceGroup);return}let target=[...document.querySelectorAll('#content [data-candidate]')].find(el=>el.dataset.candidate===id);if(!target){toast('该引用暂无可显示的详情，请先更新对应候选。');return}for(let parent=target.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;const root=$('#content');root.scrollTo({top:root.scrollTop+target.getBoundingClientRect().top-root.getBoundingClientRect().top-((root.querySelector('.current-stay')?.getBoundingClientRect().height||0)+18),behavior:'smooth'});target.classList.add('reference-highlight');setTimeout(()=>target.classList.remove('reference-highlight'),2200)});
function knowledgeHTML(){const previous=tab;tab='knowledge';const html=content();tab=previous;return html}
$('#sources-button').onclick=()=>{$('#knowledge-content').innerHTML=knowledgeHTML();$('#knowledge-dialog').showModal()};
$('#knowledge-dialog').addEventListener('click',e=>{const d=e.currentTarget,r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close()});
function deferRecovery(){recoveryDeferred=true;$('#recovery-dialog').close();$('#recovery-reminder').hidden=!pendingRecovery;positionHandle()}
$('#close-recovery').onclick=deferRecovery;
$('#reopen-recovery').onclick=()=>{if(pendingRecovery)showRecovery(pendingRecovery)};
$('#recovery-dialog').addEventListener('close',()=>{$('#recovery-reminder').hidden=!pendingRecovery});

const baseLive=renderLive;renderLive=function(){const root=jobUI?.root_action||jobUI?.action;if(root&& !['chat','plan','complete_spots','complete_hotel','skip_hotel','choose_destination','discover_destinations'].includes(root)){$('#live-reply')?.remove();return}baseLive()};
