const {chromium}=require('C:/Users/asus/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const p=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[],calls=[],mapRequests=[];let mapDelay=100,mapCompleted=0;
 p.on('pageerror',e=>errors.push(e.message));
 const source={name:'接口来源',url:'https://developer.amap.com/',queried_at:'2026-10-07'};
 const s={id:'s',name:'湖畔景区',kind:'spot',location:'120.14,30.25',address:'湖岸路',rating:4.7,opening:'09:00–22:00',recommendation:'沿湖欣赏自然风景，结合附近步道慢行，建议保留休息时间。'.repeat(5),photos:['https://example.invalid/photo.jpg'],source,visit_suggestion:{date:'2026-10-11',period:'evening',reason:'晚间可结合湖岸夜景，具体开放以出游当天为准。'}};
 const h={id:'h',name:'湖畔酒店',kind:'hotel',location:'120.15,30.26',address:'湖畔路',price:240,source,recommendation_basis:'结合已选景点分布比较住宿区域。',detail:{roomTypes:[{roomTypeName:'悦享大床房',bedType:'大床',maxOccupancy:2,ratePlans:[{rmbPrices:240,mealText:'无早餐',cancelText:'入住前可取消'}]}]},room_choices:[{id:'r',name:'悦享大床房',room_index:0,rate_index:0}]};
 const f={id:'f',name:'湖岸餐厅',kind:'food',location:'120.145,30.251',address:'湖岸街',cost:80,opening:'11:00–21:00',recommendation_basis:'午餐可结合湖畔景区周边活动安排，距参照点直线约0.5公里。',source};
 let w={id:'v8',title:'杭州旅行',revision:0,requirements:{city:'杭州',origin:'郑州',start_date:'2026-10-10',days:3,adults:1},catalog:{s,h,f,b:{id:'b',name:'G2',kind:'train',direction:'return',departure:'2026-10-13 18:00',arrival:'2026-10-13 22:00',seats:99}},selected_spots:['s'],spots_confirmed:true,hotel:h,selected_room:null,messages:[],tickets:{},trace:[],ui:{view:'spot',status:'ready'},spot_page:{page:1,pages:1,ids:['s']},hotel_query:{ids:['h']},next_step:{message:'请选择房型',view:'hotel'},selected_transport:{name:'G1',selection_status:'confirmed'},transport_queries:{},meal_choices:{}};
 // Long card list makes scroll-retention measurable without real user records.
 for(let i=0;i<10;i++){w.catalog['h'+i]={...h,id:'h'+i,name:'其他酒店'+i,detail:null};w.hotel_query.ids.push('h'+i)}
 let request,jid=0;
 await p.route('**/api/**',async r=>{
  const url=r.request().url();let data;
  if(url.includes('/map-image')){mapRequests.push(url);await new Promise(resolve=>setTimeout(resolve,mapDelay));try{await r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="768"><rect width="1024" height="768" fill="#e8edf5"/><text x="450" y="390" fill="#7187ae">UI delayed basemap</text></svg>'});mapCompleted++}catch{}return}
  if(url.includes('/auth/me'))data={user:{id:'test',nickname:'检查'},csrf_token:'test'};
  else if(url.includes('/actions')){request=r.request().postDataJSON();calls.push(request);data={job_id:'j'+(++jid)}}
  else if(url.includes('/events')){
   const a=request.action;w.revision++;w.ui={action:a,status:'ready'};
   if(a==='chat'){w.messages.push({role:'user',content:request.text},{role:'assistant',content:'已收到，请先完成当前选择，再继续下一步。'});w.ui.view='spot'}
   if(a==='visit_schedule'){w.visit_requests={[request.args.visit_requests[0].candidate_id]:request.args.visit_requests[0]};w.ui.view='spot'}
   if(a==='select_room'){w.selected_room={id:'r',name:'悦享大床房',quantity:1,price:240};w.ui.view='hotel';w.feedback={id:'j'+jid,text:'房型已保存'}}
   if(a==='train'){w.query_controls={kind:'train',direction:'outbound',departure_date:'2026-10-10',time_start:'11:00',time_end:'14:00',train_type:request.args.train_type};w.ui={...w.ui,view:'transport',controls:w.query_controls};w.transport={kind:'train',direction:'outbound',items:[]};w.transport_queries['train:outbound']=w.transport}
   if(a==='select'){w.selected_return=w.catalog.b;w.ui={...w.ui,view:'transport',suggested_view:'food'};w.next_step={view:'food',action:'search_foods',label:'查看周边餐厅',message:'请先查看餐饮安排，可选择餐厅或自行安排。'};w.messages.push({role:'assistant',content:'往返班次已确认，下一步请查看餐饮安排。'})}
   if(a==='search_foods'){w.food_query={ids:['f'],anchor:'湖畔景区',scope:'周边5公里'};w.ui.view='food'}
   if(a==='complete_food'){w.dining_reviewed=true;w.ui.view='plan';w.next_step={action:'plan',view:'plan',label:'生成计划书',message:'可以生成计划书。'}}
   if(a==='plan'){w.plan={title:'旅行计划',created:'2026-10-07T10:00',stale:false,days:[{date:'2026-10-11',theme:'湖岸慢游',events:[{candidate_id:'s',kind:'spot',name:s.name,start:'18:00',end:'19:00',duration:60,note:'建议慢行',poi:s}]}],packing:[],todos:[],warnings:[],guides:[],budget:{unknown:[]}};w.ui.view='plan';w.messages.push({role:'assistant',content:'计划书已生成，请查看。如需调整，直接发送消息。'});w.next_step={message:'请查看计划书，可直接发送调整要求。',view:'plan'}}
   data={id:'j'+jid,status:'completed',action:a,ui:w.ui,workspace:w};await r.fulfill({contentType:'text/event-stream',body:'event: done\ndata: '+JSON.stringify(data)+'\n\n'});return;
  }else if(url.includes('/workspaces/latest'))data=w;
  else if(url.includes('/workspaces'))data={items:[],total:0};
  else data={configured:true,tools:[]};
  await r.fulfill({contentType:'application/json',body:JSON.stringify(data)});
 });
 await p.route('https://example.invalid/**',r=>r.abort());
 const idle=()=>p.waitForSelector('#progress[hidden]',{state:'attached'});
 try{
  await p.goto('http://127.0.0.1:8767/');await p.waitForSelector('#application:not([hidden])');
  await p.fill('#message','想比较一下');await p.click('#send');await idle();assert.match(await p.locator('#messages').innerText(),/欢迎使用识途/);
  const card=p.locator('#content [data-candidate="s"]');assert.equal(await card.locator('.spot-description').count(),0);assert.doesNotMatch(await card.innerText(),/门票与预约|评分不代表实时客流/);
  await card.locator('h3').click();await p.waitForSelector('#candidate-dialog[open]');assert.match(await p.locator('#candidate-modal-body').innerText(),/门票与预约/);assert.equal(await p.locator('.place-photos').count(),1);
  await p.selectOption('#visit-form [name="date"]','2026-10-11');await p.selectOption('#visit-form [name="period"]','evening');await p.click('#visit-form button');await idle();assert.equal(calls.at(-1).action,'visit_schedule');assert.equal(calls.at(-1).args.visit_requests[0].period,'evening');
  await p.screenshot({path:'.展示检查/新版-v8-景点详情.png'});await p.keyboard.press('Escape');
  await p.click('#workflow [data-tab="hotel"]');await p.waitForTimeout(350);await p.evaluate(()=>{const root=document.querySelector('#content');root.style.scrollBehavior='auto';root.scrollTop=110;root.style.scrollBehavior=''});const old=await p.locator('#content').evaluate(e=>e.scrollTop);assert.ok(old>=100);
  await p.locator('#content [data-candidate="h"] h3').click({force:true});await p.waitForSelector('#candidate-dialog[open]');await p.locator('#candidate-dialog [data-room="r"]').click();await idle();assert.equal(await p.locator('#candidate-dialog').evaluate(e=>e.open),false);assert.ok(Math.abs(await p.locator('#content').evaluate(e=>e.scrollTop)-old)<10);assert.match(await p.locator('.current-stay').innerText(),/悦享大床房/);assert.ok((await p.locator('.current-stay').boundingBox()).height<65);
  await p.screenshot({path:'.展示检查/新版-v8-住宿缩略.png'});
  await p.click('#workflow [data-tab="transport"]');await p.fill('#time-start','11:00');await p.fill('#time-end','14:00');await p.selectOption('#train-type','highspeed');await idle();assert.equal(calls.at(-1).action,'train');assert.equal(calls.at(-1).args.train_type,'highspeed');assert.equal(calls.at(-1).args.time_start,'11:00');assert.doesNotMatch(await p.locator('#content').innerText(),/可独立调整班次日期/);assert.equal(await p.locator('.train-type-label').count(),1);
  await p.screenshot({path:'.展示检查/新版-v8-交通筛选.png'});
  await p.evaluate(()=>{transportDirection='return';workspace.transport_queries['train:return']={items:[workspace.catalog.b]};render()});await p.click('[data-select="b"]');await p.waitForTimeout(300);await idle();assert.match(await p.locator('#workspace-title').innerText(),/餐饮/);assert.equal(calls.at(-1).action,'search_foods');assert.match(await p.locator('#content [data-candidate="f"]').innerText(),/推荐理由|人均/);
  await p.click('[data-action="complete_food"]');await idle();assert.match(await p.locator('#workspace-title').innerText(),/计划/);await p.locator('#content [data-action="plan"]').first().click();await idle();assert.match(await p.locator('#messages .message').last().innerText(),/请查看.*调整/);
  await p.click('#map-button');await p.selectOption('#map-day','2026-10-11');assert.match(await p.locator('#content').innerText(),/地点顺序示意/);assert.equal(await p.locator('#content .map-legend [data-open-candidate="s"]').count(),1);
  const m=p.locator('#content .location-map');await p.waitForFunction(()=>document.querySelector('#content .location-map .map-update-text')?.textContent==='');
  const initial=Number(await m.getAttribute('data-map-zoom')),origin=JSON.parse(await m.getAttribute('data-map-center')),canvas=m.locator('canvas');await canvas.scrollIntoViewIfNeeded();
  await m.locator('[data-map-zoom-action="in"]').click();assert.equal(Number(await m.getAttribute('data-map-zoom')),initial+1);assert.equal(await m.locator('.map-zoom-level').innerText(),'200%');await m.locator('[data-map-zoom-action="reset"]').click();assert.equal(await m.locator('.map-zoom-level').innerText(),'100%');
  const rect=await canvas.boundingBox(),pointer={x:Math.round(rect.x+rect.width*.72),y:Math.round(rect.y+rect.height*.57)};
  const anchored=()=>m.evaluate((el,p)=>{const offset=mapPointerOffset(el.querySelector('.map-stage'),{clientX:p.x,clientY:p.y}),c=mapWorld(...JSON.parse(el.dataset.mapCenter)),scale=256*Math.pow(2,Number(el.dataset.mapZoom));return c.map((n,i)=>n+offset[i]/scale)},pointer);
  const anchor=await anchored();mapDelay=1600;const finishedBefore=mapCompleted,paintBefore=Number(await m.getAttribute('data-map-paint'));await p.mouse.move(pointer.x,pointer.y);await p.mouse.wheel(0,-120);await p.waitForTimeout(60);assert.equal(Number(await m.getAttribute('data-map-zoom')),initial+1);assert.equal(await m.locator('.map-zoom-level').innerText(),'200%');assert.ok(Number(await m.getAttribute('data-map-paint'))>paintBefore);assert.equal(mapCompleted,finishedBefore,'动画不能等到底图响应才更新');let after=await anchored();assert.ok(after.every((n,i)=>Math.abs(n-anchor[i])<1e-10));
  await p.mouse.wheel(0,120);await p.waitForTimeout(60);await p.mouse.dblclick(pointer.x,pointer.y);assert.equal(Number(await m.getAttribute('data-map-zoom')),initial+1);after=await anchored();assert.ok(after.every((n,i)=>Math.abs(n-anchor[i])<1e-10));await m.locator('[data-map-zoom-action="reset"]').click();
  await p.waitForTimeout(20);const beforeDrag=mapRequests.length,oldCenter=await m.getAttribute('data-map-center'),point={x:Math.round(rect.x+rect.width/2),y:Math.round(rect.y+rect.height/2)};await p.mouse.move(point.x,point.y);await p.mouse.down();await p.mouse.move(point.x+70,point.y+30,{steps:8});assert.notEqual(await m.getAttribute('data-map-center'),oldCenter,'拖动应立即改变中心');assert.equal(mapRequests.length,beforeDrag,'拖动过程中不应逐步请求整张底图');await p.mouse.up();await p.waitForTimeout(300);assert.ok(mapRequests.length<=beforeDrag+1);
  const currentZoom=Number(await m.getAttribute('data-map-zoom'));await m.locator('[data-map-zoom-action="center"]').click();assert.deepEqual(JSON.parse(await m.getAttribute('data-map-center')),origin);assert.equal(Number(await m.getAttribute('data-map-zoom')),currentZoom,'重置中心不改比例');
  await m.locator('[data-map-zoom-action="nation"]').click();assert.equal(Number(await m.getAttribute('data-map-zoom')),3);assert.deepEqual(JSON.parse(await m.getAttribute('data-map-center')),[104.1954,35.8617]);await m.locator('[data-map-zoom-action="in"]').click();assert.equal(Number(await m.getAttribute('data-map-zoom')),4);await m.locator('[data-map-zoom-action="out"]').click();await m.locator('[data-map-zoom-action="reset"]').click();assert.equal(await m.locator('.map-zoom-level').innerText(),'100%');assert.deepEqual(JSON.parse(await m.getAttribute('data-map-center')),origin);
  await p.evaluate(()=>{const root=document.querySelector('#content .location-map');const c=mapControllers.get(root);c.zoom=17;c.sync()});assert.equal(await m.locator('[data-map-zoom-action="in"]').isDisabled(),true);await m.locator('[data-map-zoom-action="reset"]').click();
  await p.locator('#content .map-legend [data-open-candidate="s"]').click();const dm=p.locator('#candidate-dialog .location-map');await p.waitForSelector('#candidate-dialog .map-stage');await p.waitForTimeout(50);const dlevel=Number(await dm.getAttribute('data-map-zoom'));await dm.locator('[data-map-zoom-action="in"]').click();assert.equal(Number(await dm.getAttribute('data-map-zoom')),dlevel+1);await dm.locator('[data-map-zoom-action="nation"]').click();assert.equal(Number(await dm.getAttribute('data-map-zoom')),3);await p.keyboard.press('Escape');mapDelay=100;await p.screenshot({path:'.展示检查/新版-v9-交互地图.png'});
  for(const width of [390,768,1600]){await p.setViewportSize({width,height:1000});await p.click('#workflow [data-tab="transport"]');await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const a=await p.locator('.transport-date').boundingBox(),b=await p.locator('.transport-time').boundingBox();assert.ok(Math.abs(a.y-b.y)<5);await p.screenshot({path:`.展示检查/新版-v8-布局-${width}.png`})}
  assert.deepEqual(errors,[]);fs.writeFileSync('data/runtime/browser-map-v9.json',JSON.stringify({passed:true,fixture:true,checks:['welcome-retained','card-dialog','ticket-moved','image-fallback','date-intent','room-selection-scroll','two-line-stay','automatic-type-query','dining-step-and-auto-query','plan-review-guidance','main-and-detail-map','pointer-wheel-anchor','double-click-anchor','percent-and-reset','drag-response-before-delayed-image','coalesced-drag-request','independent-center-reset','national-view','cached-snapshot','390/768/1600'],errors},null,2));console.log('INTERACTIVE MAP V9 PASSED');
 }catch(e){await p.screenshot({path:'.展示检查/map-v9-failure.png'});throw e}finally{await browser.close()}
})().catch(e=>{console.error(e.stack);process.exitCode=1});
