"""LangGraph 工作流的阶段名。

`CONTRACTS.md` §11 只给出一个示例值 `VALIDATING`，没有定义完整取值集合
（已登记在 `docs/contract-open-questions.md` 第 1 节）。
本文件是 C 线在实际实现中使用的阶段词汇表，待三人确认后写回契约。

阶段推进顺序（P0）：

```text
CREATED
  → PARSING_REQUEST → CHECKING_FIELDS
      → ASKING_CLARIFICATION（返回用户追问，等待补充）
      → RETRIEVING_DESTINATIONS
          → RECOMMENDING_DESTINATIONS → AWAITING_DESTINATION_CONFIRMATION
          → INSUFFICIENT_DATA（知识库覆盖不足，明确降级）
C3（已完成）：AWAITING_DESTINATION_CONFIRMATION 之前，若用户已点名目的地，
              先 FETCHING_RESOURCES → FILTERING_RESOURCES 把不可用资源挡在规划之前，
              再回到 AWAITING_DESTINATION_CONFIRMATION 等待用户确认。
C4 起接入：PLANNING → VALIDATING →（REPAIRING）→ READY
```
"""

from enum import Enum


class PlanStage(str, Enum):
    CREATED = "CREATED"
    PARSING_REQUEST = "PARSING_REQUEST"
    CHECKING_FIELDS = "CHECKING_FIELDS"
    ASKING_CLARIFICATION = "ASKING_CLARIFICATION"
    RETRIEVING_DESTINATIONS = "RETRIEVING_DESTINATIONS"
    RECOMMENDING_DESTINATIONS = "RECOMMENDING_DESTINATIONS"
    #: 抓取用户点名目的地的资源候选（C3）
    FETCHING_RESOURCES = "FETCHING_RESOURCES"
    #: 规划前的可用性前置过滤（C3，`CONTRACTS.md` §14 不变量 2）
    FILTERING_RESOURCES = "FILTERING_RESOURCES"
    AWAITING_DESTINATION_CONFIRMATION = "AWAITING_DESTINATION_CONFIRMATION"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    # 以下阶段在 C3–C6 实现，这里先占位，避免后续改名影响已写好的判断
    PLANNING = "PLANNING"
    VALIDATING = "VALIDATING"
    REPAIRING = "REPAIRING"
    READY = "READY"

    def __str__(self) -> str:  # pragma: no cover - 仅用于可读输出
        return self.value
